# Generated by Django 2.2.5 on 2020-02-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('active', models.CharField(default='Y', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stname', models.CharField(max_length=100)),
                ('stadr', models.CharField(max_length=100)),
                ('stage', models.IntegerField()),
                ('stfees', models.FloatField()),
                ('active', models.CharField(default='Y', max_length=100)),
            ],
        ),
    ]
